PLUGIN_NAME=		privoxy
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	4
PLUGIN_COMMENT=		Manage Privoxy proxy tool
PLUGIN_DEPENDS=		privoxy
PLUGIN_MAINTAINER=	d.vargas@infraops.fr

.include "../../Mk/plugins.mk"
