PLUGIN_NAME=		sockdiops
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	2
PLUGIN_COMMENT=		InfraOpS tools to manage interconnexions
PLUGIN_DEPENDS=		dante graphviz
PLUGIN_MAINTAINER=	d.vargas@infraops.fr

.include "../../Mk/plugins.mk"
